import { Noto_Sans, Geist_Mono, Protest_Revolution } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./provider";
import { Header } from "@/components/layout/Header";
import { UserProvider } from "./UserProvider";
import { Footer } from "@/components/layout/Footer";
import PageLoading from "@/components/loading/PageLoading";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const protestRevolution = Protest_Revolution({
  variable: "--font-protest_revolution",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "E-Restaurant",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${geistMono.variable} ${protestRevolution.variable} antialiased`}
      >
        <AuthProvider>
          <UserProvider>
            <PageLoading />
            <Header />
            {children}
            <Footer />
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
